on:
  push:
defaults:
  run:
    shell: bash
  
jobs:
  react-native:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Init
      run: |
        npm install
        npm install -g appcenter-cli

    - name: build
      run: |
        cd android
        chmod +x gradlew
        ./gradlew build
        find . -name '*.apk'

    - name: deploy
      run: |
        cd android
        appcenter distribute release\
         --app drdagerm/cloudcamp\
         --file app/build/outputs/apk/debug/app-debug.apk\
         --group "Collaborators"\
         --token ${{ secrets.APP_CENTER_TOKEN }}
