on:
  push:
defaults:
  run:
    shell: bash
  
jobs:
  react-native:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: |
        java --version
        node --version
        npm --version
        gradle --version
        docker 

    - name: build
      run: |
        cd android
        chmod +x gradlew
        ./gradlew build


